version: '3'

services:
  game_scrapper:
    image: game-picker/game-scrapper
    container_name: game-scrapper
    restart: always
    environment:
      TZ: Asia/Novosibirsk
    networks: 
      - game_picker_network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${POSTGRES_TIMEZONE}
      PGTZ: ${POSTGRES_TIMEZONE}
    shm_size: ${POSTGRES_SHM_SIZE:-4gb}
    restart: always
    networks: 
      - game_picker_network

networks: 
  game_picker_network:
