build-17:
	docker pull azul/zulu-openjdk:17
	docker tag azul/zulu-openjdk:17 pi41:5000/java-base-image:17
	docker push pi41:5000/java-base-image:17

build-11:
	docker pull azul/zulu-openjdk:11
	docker tag azul/zulu-openjdk:11 pi41:5000/java-base-image:11-jre
	docker push pi41:5000/java-base-image:11-jre
