version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    mem_limit: 1024m
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${POSTGRES_TIMEZONE}
      - PGTZ=${POSTGRES_TIMEZONE}
    networks:
      - gamepickernet
    command: # файл конфигурации нельзя расположить по стандартному пути, т.к. entrypoint его перезапишет при старте
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf

  backend:
    image: pi41:5000/game-picker/backend:latest
    restart: always
    environment:
      - TZ=${POSTGRES_TIMEZONE}
      - GAME-SCRAPPER_INTERVAL=1h
      - MEDIA-DOWNLOADER_INTERVAL=1h
      - POSTGRES_HOST=postgres
      - DATABASE_NAME=${POSTGRES_DATABASE_NAME}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - LOGGING_LEVEL_RU_TWOSHOES=DEBUG
      - MINIO_URL=http://192.168.0.6:9002
    mem_limit: 1024m
    depends_on:
      - postgres
    networks:
      - gamepickernet

networks:
  gamepickernet:

volumes:
  postgres:
