version: '3'

services:
  minio-server:
    image: minio/minio:latest
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=OREshnitel123
      # - MINIO_OPTS="--console-address :9001"
    ports:
      # console
      - 9001:9001
      # api
      - 9002:9000
    networks:
      - minio_net
    volumes:
      - minio_volume:/data:rw
    command:
      - server
      - /data
      - --console-address
      - ":9001"

networks:
  minio_net:

volumes:
  minio_volume:
